# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A random walk Metropolis sampler
#' @description A random walk Metropolis sampler for generating the standard Laplace distribution using Rcpp
#' @param sigma the stardard deviation of the random walk
#' @param x_0 the start point
#' @param N the number of samples
#' @return a random sample of size \code{n} as well as the number of rejections
#' @examples
#' \dontrun{
#' rnC <- gibbsC(100,10)
#' par(mfrow=c(2,1));
#' plot(rnC[,1],type='l')
#' plot(rnC[,2],type='l')
#' }
#' @export
rw_MetropolisC <- function(sigma, x_0, N) {
    .Call('_StatComp20023_rw_MetropolisC', PACKAGE = 'StatComp20023', sigma, x_0, N)
}

